# chez-cmark-gfm

CHEZ        ?= chez
CC          ?= cc
UNAME_S     := $(shell uname -s)

ifeq ($(UNAME_S),Darwin)
  SHLIB_EXT := dylib
  SHLIB_LDFLAGS := -dynamiclib
else
  SHLIB_EXT := so
  SHLIB_LDFLAGS := -shared -fPIC
endif

BUILD_DIR   := build
LIB_DIR     := $(BUILD_DIR)/lib
SHIM        := $(LIB_DIR)/libchezcmarkgfm.$(SHLIB_EXT)
CONFIG_SLS  := src/cmark/gfm/private/config.sls
VENDOR_DIR  := vendor/cmark-gfm
VENDOR_BUILD:= $(BUILD_DIR)/vendor

CFLAGS_BASE := -std=c99 -Wall -Wextra -Werror -Wconversion -Wshadow -Wpointer-arith -fPIC
CFLAGS_DEV  := $(CFLAGS_BASE) -g -O0 -DCHEZ_CMARK_DEBUG_COUNTERS
CFLAGS_PROD := $(CFLAGS_BASE) -O2

# --- native dependency discovery (ADR-0001) --------------------------
HAVE_PKG := $(shell pkg-config --exists libcmark-gfm && echo yes || echo no)

ifeq ($(HAVE_PKG),yes)
  CMARK_CFLAGS := $(shell pkg-config --cflags libcmark-gfm)
  CMARK_LIBDIR := $(shell pkg-config --variable=libdir libcmark-gfm)
  # Upstream ships no .pc for the extensions library: link it manually.
  CMARK_LIBS   := $(shell pkg-config --libs libcmark-gfm) \
                  -L$(CMARK_LIBDIR) -lcmark-gfm-extensions
else
  CMARK_CFLAGS := -I$(VENDOR_BUILD)/src -I$(VENDOR_DIR)/src \
                  -I$(VENDOR_DIR)/extensions
  # The vendored copy is built and linked as SHARED libraries (design spec
  # 6.1), never static. cmark-gfm's static archives are built with
  # CMAKE_C_VISIBILITY_PRESET hidden plus CMARK_GFM_STATIC_DEFINE, which
  # hides every cmark symbol from whatever links them. native.sls resolves
  # cmark's entry points directly via foreign-procedure at runtime, so those
  # symbols have to stay visible in a real shared object -- static linking
  # cannot satisfy that no matter what the archives are named.
  #
  # Each shared library gets its own -Wl,-rpath entry, absolute and recorded
  # at build time, so the shim resolves them at load time with no system
  # library search and no dependence on the working directory or
  # LD_LIBRARY_PATH/DYLD_LIBRARY_PATH -- the same guarantee the pkg-config
  # path gets from the installed library's own rpath/soname handling.
  #
  # Extensions FIRST, then core, on the link line: kept from the static case
  # for consistency, though it no longer determines symbol resolution --
  # shared objects carry their own recorded dependencies (libcmark-gfm-
  # extensions already depends on libcmark-gfm via its own CMake target).
  CMARK_VENDOR_LIBDIR_EXT := $(abspath $(VENDOR_BUILD)/extensions)
  CMARK_VENDOR_LIBDIR_SRC := $(abspath $(VENDOR_BUILD)/src)
  CMARK_LIBS   := -L$(CMARK_VENDOR_LIBDIR_EXT) -lcmark-gfm-extensions \
                  -L$(CMARK_VENDOR_LIBDIR_SRC) -lcmark-gfm \
                  -Wl,-rpath,$(CMARK_VENDOR_LIBDIR_EXT) \
                  -Wl,-rpath,$(CMARK_VENDOR_LIBDIR_SRC)
endif

CHEZ_LIBDIRS := src:.akku/lib
TESTS        := $(wildcard tests/test-*.sps)

.PHONY: all build dev test test-memory vendor clean prod deps-info

all: build

deps-info:
	@echo "cmark-gfm source : $(if $(filter yes,$(HAVE_PKG)),pkg-config,vendored)"
	@echo "shim             : $(SHIM)"

build: $(SHIM) $(CONFIG_SLS)

$(LIB_DIR):
	mkdir -p $(LIB_DIR)

ifeq ($(HAVE_PKG),no)
$(SHIM): vendor
endif

$(SHIM): src/cmark-gfm-shim.c src/cmark-gfm-shim.h | $(LIB_DIR)
	$(CC) $(CFLAGS_DEV) $(CMARK_CFLAGS) $(SHLIB_LDFLAGS) \
	      -o $@ src/cmark-gfm-shim.c $(CMARK_LIBS)

# config.sls carries the shim's ABSOLUTE path so the loader never searches.
$(CONFIG_SLS): $(SHIM)
	@mkdir -p $(dir $@)
	@printf '%s\n' \
	  '#!r6rs' \
	  ';; GENERATED by make -- do not edit, do not commit.' \
	  '(library (cmark gfm private config)' \
	  '  (export shim-path cmark-supported-version-range)' \
	  '  (import (rnrs))' \
	  '  (define shim-path "$(abspath $(SHIM))")' \
	  '  (define cmark-supported-version-range (quote (#x001d0000 . #x001dffff))))' \
	  > $@

vendor:
	git submodule update --init --recursive
	cmake -S $(VENDOR_DIR) -B $(VENDOR_BUILD) \
	  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	  -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
	  -DCMARK_TESTS=OFF -DCMARK_SHARED=ON -DCMARK_STATIC=OFF
	cmake --build $(VENDOR_BUILD) -j

dev: build
	CHEZSCHEMELIBDIRS=$(CHEZ_LIBDIRS) $(CHEZ)

# Each suite sets its own exit status. Keep going after a failure so one
# broken suite cannot hide the others, then fail the target if any failed.
test: build
	@fail=0; \
	for t in $(TESTS); do \
	  echo "=== $$t ==="; \
	  CHEZSCHEMELIBDIRS=$(CHEZ_LIBDIRS) $(CHEZ) --program $$t || fail=1; \
	done; \
	if [ $$fail -eq 0 ]; then echo "ALL SUITES PASSED"; \
	else echo "SUITE FAILED"; fi; \
	exit $$fail

test-memory: build
ifeq ($(UNAME_S),Linux)
	@for t in $(TESTS); do \
	  CHEZSCHEMELIBDIRS=$(CHEZ_LIBDIRS) valgrind --error-exitcode=9 \
	    --leak-check=full --show-leak-kinds=definite \
	    $(CHEZ) --program $$t || exit 1; \
	done
else
	@echo "macOS: ASan preload only; LeakSanitizer is unsupported on arm64."
	@echo "Leak claims must come from Linux CI (ADR-0003)."
	CHEZSCHEMELIBDIRS=$(CHEZ_LIBDIRS) \
	  DYLD_INSERT_LIBRARIES="$$(command ls $$(dirname $$(xcrun --find clang))/../lib/clang/*/lib/darwin/libclang_rt.asan_osx_dynamic.dylib | head -1)" \
	  ASAN_OPTIONS=detect_leaks=0 \
	  sh -c 'for t in $(TESTS); do $(CHEZ) --program $$t || exit 1; done'
endif

# prod compiles directly rather than reusing $(SHIM), so it needs the same
# vendored-build gate that $(SHIM) gets above; without it `make prod` fails on
# a machine where pkg-config cannot see cmark-gfm.
ifeq ($(HAVE_PKG),no)
prod: vendor
endif

prod: clean
	mkdir -p $(LIB_DIR)
	$(CC) $(CFLAGS_PROD) $(CMARK_CFLAGS) $(SHLIB_LDFLAGS) \
	      -o $(SHIM) src/cmark-gfm-shim.c $(CMARK_LIBS)
	$(MAKE) $(CONFIG_SLS)

clean:
	rm -rf $(BUILD_DIR) $(CONFIG_SLS)
